### ISSUE TITLE
Add OpenShift Control Plane Nodes as backend listeners for the Ingress LB

### ISSUE THREAD

**Issue by makentenza** [oracle-quickstart/oci-openshift#26]
For scenarios where the total number of Hosts in the cluster is less than 5, the Assisted Installer will make the Control Plane Nodes schedulable by default resulting in the Ingress Operator staying in a failure state preventing the cluster bootstrap process from completing successfully.

The Ingress LB should add by default the Control Plane Nodes as backend listeners so this issue can be prevented when deploying SNO and compact clusters.

For larger clusters with (5 nodes or more), a new feature has also been introduced in Assisted Installer that allows users, as part of installation setup, to schedule workloads so that they run on Control Plane Nodes as well as worker nodes

**Comment by davidfoster0127** [comment]
While testing the changes for this, I ran into an issue where there is a limit to the number of load balancer attachments on an instance pool. We are trying to have 6 total attachments and the current limit is 5. I have raised a ticket requesting for the limit to be increased to 6 globally. I'm looking for a more creative workaround in the meantime.

**Comment by davidfoster0127** [comment]
Mentioned in a few places now, but the limit increase has been applied globally for all tenancies.
