### ISSUE TITLE
Why Multi-AD deployment with seperate instance pools

### ISSUE THREAD

**Issue by RichardORCL** [oracle-quickstart/oci-openshift#38]
The new terraform update creates in multi-ad regions now automatically the compute and control nodes distributed across ADs. 

I do not understand this implementation. The terraform update creates a Instance Pool for each AD, while instance pools natively support having multi ADs inside them.

Why are there now so many instance pools created? instead of just using multiple ADs inside the instance pool?

@vin-9816

**Comment by vinayak-oci** [comment]
Thank you for bringing this to our attention. We're currently investigating the implementation and will push the latest changes shortly to address this
