### ISSUE TITLE
Delay needed after tag namespace creation

### ISSUE THREAD

**Issue by RichardORCL** [oracle-quickstart/oci-openshift#40]
On first apply, the terraform always fails with error:

```
Error: 400-InvalidParameter, Failed to validate tags: TagNamespace openshift-os does not exists
Suggestion: Please update the parameter(s) in the Terraform config as per error message Failed to validate tags: TagNamespace openshift-os does not exists
```

The tag namespace is created, but can not directly be used by the following resources. It needs at least a 10 second delay dependency.

When clicking the 2nd time Apply in resource manager, the terraform executes further normally.

**Comment by dfoster-oracle** [comment]
After investigating, we've decided to rollback some of the tagging changes causing this issue to give us more time to work with other teams and fix this issue in a better way. The flow of applying the stack should now be less painful.
