### ISSUE TITLE
Open shift configuration does not proceed correctly

### ISSUE THREAD

**Issue by kimsh92** [oracle-quickstart/oci-openshift#8]
Hello.
When i install Openshift using Assistant Installer according to the github's oci-openshift procedure, the state changes to the "Installing Pending User Action" state after a certain period of time and does not proceed any further.

Do I need to do any additional settings?

**Comment by julienlim** [comment]
Hi @kimsh92. Thanks for your inquiry.  Can you share a screenshot of what you're seeing?

Red Hat OpenShift on Oracle Cloud Infrastructure with Virtual Machines (VMs) is currently available for [Developer Preview](https://access.redhat.com/support/offerings/devpreview).

Note that Red Hat OpenShift on Oracle Cloud Infrastructure requires the use of [Red Hat Enterprise Linux (RHEL) certified Oracle Cloud Infrastructure shapes](https://catalog.redhat.com/cloud/detail/216977) (instance types) with yourOpen Shift subscription to deploy Red Hat OpenShift on Oracle Cloud Infrastructure. 

Please complete this [Red Hat OpenShift on Oracle Cloud Infrastructure Developer Preview Request Form](https://forms.gle/cw1QxkETrnspHsre6) to request access to deploy OpenShift on Oracle Cloud Infrastructure.

**Comment by ThomasKim92** [comment]
Version : 4.14 (Dev Preview)

![image](https://github.com/oracle-quickstart/oci-openshift/assets/85597597/5f40311a-cc71-4e7f-ae89-c6f354decf66)

![image](https://github.com/oracle-quickstart/oci-openshift/assets/85597597/713d64b6-5e24-45d1-b34c-584b3fe42248)

and i can not access Request Form
![image](https://github.com/oracle-quickstart/oci-openshift/assets/85597597/6c0b9fd0-8da2-4850-9795-0e94ca2279bc)

**Comment by nikhisin3001** [comment]
There is an old issue and has no comments lately. Closing the issue.
